type Coin{
    coin_id: String! @unique
    old_24h_volume:Float!
    new_24h_volume:Float!
}
type VolumePreHr{
    coin:String!
    hr_id:Int!
    volume:Float!
}

type Query {
    allCoins:[Coin]
    allVolumePreHrs:[VolumePreHr]
    findVolumePreHrsByCoinId(coin:String!):[VolumePreHr]
    findCoinByCoinID(coin_id:String!):Coin
}

type Mutation {
    updataCoinVolById(coin_id:String!,new_24h_volume:Float!):Coin @resolver(name:"updataCoinVolById")
    createVolPerHr(coin_id:String!):VolumePreHr @resolver(name:"createVolPerHr")
    deleteVolPerHr(coin_id:String!):VolumePreHr @resolver(name:"deleteVolPerHr")
}

