    type  coin{
        coin_id: String!
        h24_volume_pre_hour: [volume_pre_hr]
        last_h24_volume:Float
    }
    type volume_pre_hr{
        coin: coin!
        hr_id: Int!
        volume:Float!
    }

    type Query {
        getVolumePreHour(coidID:String):volume_pre_hr;
    }

    type Mutation {
        addCoin(newCoin: coin):coin
        updateVolume(newVolume:h24_volume_pre_hour):h24_volume_pre_hour
    }